import Head from "next/head";
import Header from "@/componetns/Header";
import Partfolio from "@/componetns/Partfolio";
import { useScroll, motion, useTransform } from "framer-motion";

export default function Home() {
  const { scrollY } = useScroll();
  const someBorders = [200, 400];
  return (
    <>
      <Head>
        <title>scroll paralax/</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Partfolio />
    </>
  );
}
{
  /*  */
}
